name: Déploiement Terraform

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout du code source
      uses: actions/checkout@v2

    - name: Configuration de l'environnement
      run: |
        echo "$GOOGLE_CREDENTIALS" > corded-evening-390420-6f56f9200f65.json
        curl -LO https://releases.hashicorp.com/terraform/1.0.0/terraform_1.0.0_linux_amd64.zip
        unzip terraform_1.0.0_linux_amd64.zip
        sudo mv terraform /usr/local/bin/
        chmod +x /usr/local/bin/terraform

    - name: Initialisation Terraform
      run: |
        terraform init

    - name: Planification Terraform
      run: |
        terraform plan

    - name: Déploiement Terraform
      run: |
        terraform apply -auto-approve
